tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-container": "#1A1A1A",
                "on-secondary-fixed-variant": "#FF5540",
                "outline": "#353535",
                "surface-container-highest": "#1A1A1A",
                "tertiary": "#FF0000",
                "primary-container": "#FF0000",
                "surface-bright": "#1A1A1A",
                "on-secondary": "#FFFFFF",
                "inverse-surface": "#FFFFFF",
                "error-dim": "#D7383B",
                "on-surface": "#FFFFFF",
                "surface-container-low": "#0E0E0E",
                "on-error-container": "#FFA8A3",
                "surface-tint": "#FF0000",
                "on-surface-variant": "#EBBBB4",
                "surface-container-lowest": "#000000",
                "surface-container-high": "#131313",
                "on-tertiary": "#FFFFFF",
                "on-tertiary-fixed": "#000000",
                "tertiary-fixed": "#FF0000",
                "surface": "#000000",
                "on-primary-fixed": "#FFFFFF",
                "error": "#FF716C",
                "on-primary": "#FFFFFF",
                "on-secondary-container": "#FFFFFF",
                "surface-variant": "#0E0E0E",
                "primary-fixed-dim": "#FF5540",
                "secondary-dim": "#353535",
                "background": "#000000",
                "surface-dim": "#000000",
                "outline-variant": "#353535",
                "secondary-fixed": "#131313",
                "on-tertiary-fixed-variant": "#FF5540",
                "surface-container": "#0E0E0E",
                "on-tertiary-container": "#000000",
                "tertiary-fixed-dim": "#FF5540",
                "primary-fixed": "#FF0000",
                "tertiary-dim": "#FF0000",
                "inverse-primary": "#AA0000",
                "on-background": "#FFFFFF",
                "secondary-fixed-dim": "#131313",
                "tertiary-container": "#FF0000",
                "error-container": "#9F0519",
                "primary": "#FF0000",
                "inverse-on-surface": "#000000",
                "secondary": "#131313",
                "on-primary-container": "#FFFFFF",
                "on-primary-fixed-variant": "#FFFFFF",
                "primary-dim": "#CC0000",
                "on-secondary-fixed": "#FFFFFF",
                "on-error": "#490006"
            },
            fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Lexend"]
            },
            borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
        },
    },
};
